name: corona
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:

  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_page_indicator: ^0.0.3
  flutter_swiper :
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  intl_translation:
  cloud_firestore:
  intl:

  scoped_model: "^0.3.0"
  easy_localization:



  google_maps_flutter: 
  location:
 
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/electropi1++.png
    - images/q1.png
    - images/q2.png
    - images/q3.png
    - images/q4.png
    - images/q5.png
    - images/q6.png
    - images/q7.png
    - images/q8.png
    - images/q9.png
    - images/q10.png
    - images/q11.png
    - images/q12.png
    - images/q13.png
    - images/bg0.png
    - images/bg1.png
    - images/bg2.png
    - images/bg3.png
    - images/bg4.png
    - images/bg5.png
    - images/bg6.png
    - images/No.png
    - images/Yes.png
    - images/homebg.png
    - images/homebg1.png
    - images/homebg2.png
    - images/homebg3.png
    - images/fastdiagnosis.png
    - images/statusgreen.png
    - images/postive.png
    - images/Contactus.png
    - images/nagtive.png
    - images/yallow.png
    - images/report.png
    - lang/en-US.json
    - lang/ar-EG.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
